service: pollen
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: eu-central-1
  memorySize: 128
functions:
  app:
    handler: app.handler
    events:
      - http:
          path: "/pollen"
          method: GET
          cors: false
